# Generated by Django 5.1 on 2024-08-22 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonym', max_length=25)),
                ('text', models.TextField(default='Yeah, yeah, very intersting.')),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test_name', max_length=25)),
                ('description', models.TextField(default='Blah blah blah')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('commentaries', models.ManyToManyField(to='tasks.commentary')),
            ],
        ),
    ]
